---
plugins:
  - '@ronilaukkarinen/stylelint-a11y'
  - stylelint-declaration-block-no-ignored-properties
rules:
  color-no-invalid-hex: true
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  string-no-newline: true
  unit-no-unknown:
    - true
    - ignoreFunctions:
        - image-set
  property-no-unknown: true
  keyframe-declaration-no-important: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  block-no-empty: true
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - local
        - global
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown:
    - true
    - ignoreTypes:
      - '^'
  media-feature-name-no-unknown: true
  at-rule-no-unknown: true
  comment-no-empty: true
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  color-named: never
  function-disallowed-list:
    - hsl
    - hsla
    - repeating-linear-gradient
    - repeating-radial-gradient
    - hwb
    - inset
    - matrix3d
    - polygon
    - rotate3d
    - scale3d
    - symbols
    - translate3d
  function-url-no-scheme-relative: true
  function-url-scheme-disallowed-list:
    - data
    - ftp
    - file
    - /^http/
  number-max-precision: 2
  time-min-milliseconds: 100
  unit-disallowed-list:
    - ex
    - cm
    - mm
    - in
    - pt
    - pc
  shorthand-property-no-redundant-values: true
  value-no-vendor-prefix:
    - true
    - ignoreValues:
        - box
  property-disallowed-list:
    - property-blacklist
    - box-decoration-break
    - break-after
    - break-before
    - break-inside
    - clip
    - hyphens
    - hanging-punctuation
    - image-orientation
    - image-rendering
    - image-resolution
    - orphans
    - perspective-origin
    - text-combine-upright
  property-no-vendor-prefix:
    - true
    - ignoreProperties:
        - line-clamp
        - box-orient
        - tap-highlight-color
        - appearance
  declaration-block-no-redundant-longhand-properties: true
  declaration-no-important: true
  declaration-block-single-line-max-declarations: 1
  selector-class-pattern:
    - '^[a-z\d-]+(__[a-z\d-]+)?(_[a-z\d-]+)?$'
    - resolveNestedSelectors: true
  selector-id-pattern: '^[a-z]+(?:[a-z\d-]+)?$'
  selector-max-attribute: 2
  selector-max-class: 2
  selector-max-combinators: 3
  selector-max-compound-selectors: 3
  selector-max-empty-lines: 0
  selector-max-id: 0
  selector-max-pseudo-class: 3
  selector-max-universal: 1
  selector-no-qualifying-type:
    - true
    - ignore:
        - attribute
  selector-no-vendor-prefix: true
  selector-pseudo-class-disallowed-list:
    - any
    - any-link
    - default
    - defined
    - dir
    - host
    - left
    - right
    - scope
  selector-pseudo-element-disallowed-list:
    - /^-moz-/i
    - /^-ms-/i
    - /^-webkit-/i
    - backdrop
    - cue
    - grammar-error
    - spelling-error
  media-feature-name-disallowed-list:
    - any-hover
    - any-pointer
    - color-gamut
    - grid
    - inverted-colors
    - max-monochrome
    - min-monochrome
    - monochrome
    - scripting
    - update
  media-feature-name-no-vendor-prefix: true
  at-rule-disallowed-list:
    - document
    - viewport
    - counter-style
    - font-feature-values
  at-rule-no-vendor-prefix: true
  comment-word-disallowed-list:
    - '/^TODO:/'
    - '/^@TODO:/'
  max-nesting-depth:
    - 5
    - ignore:
        - blockless-at-rules
  color-hex-case: lower
  font-family-name-quotes: always-where-recommended
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: never-multi-line
  function-comma-space-after: always
  function-comma-space-before: never
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: never-multi-line
  function-parentheses-space-inside: never
  function-url-quotes: always
  function-whitespace-after: always
  number-leading-zero: always
  number-no-trailing-zeros: true
  string-quotes: double
  length-zero-no-unit: true
  unit-case: lower
  value-keyword-case:
    - lower
    - camelCaseSvgKeywords: true
      ignoreKeywords:
        - '/^U\+[\w-]+$/'
  value-list-comma-newline-after: always-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  custom-property-empty-line-before:
    - always
    - except:
        - after-comment
        - after-custom-property
        - first-nested
      ignore:
        - first-nested
  property-case: lower
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-empty-line-before: never
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-trailing-semicolon: always
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always
  block-closing-brace-newline-before: always-multi-line
  block-opening-brace-newline-after: always-multi-line
  block-opening-brace-space-after: always-single-line
  block-opening-brace-space-before: always
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-quotes: always
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-descendant-combinator-no-non-space: true
  selector-pseudo-class-case: lower
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-type-case: lower
  selector-list-comma-newline-after: always
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: always-single-line
  selector-list-comma-space-before: never
  rule-empty-line-before:
    - always
    - ignore:
        - after-comment
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-case: lower
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: never-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always
  media-query-list-comma-space-before: never
  at-rule-empty-line-before: always
  at-rule-name-case: lower
  at-rule-name-space-after: always
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  comment-empty-line-before:
    - always
    - except:
        - first-nested
      ignore:
        - after-comment
        - stylelint-commands
  comment-whitespace-inside: always
  indentation: 4
  max-empty-lines: 1
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
  plugin/declaration-block-no-ignored-properties: true
